from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

try:
    from config import LabConfig, load_config
    from memory_store import estimate_tokens
    from model_provider import build_chat_model
except ImportError:
    from src.config import LabConfig, load_config
    from src.memory_store import estimate_tokens
    from src.model_provider import build_chat_model


@dataclass
class SessionState:
    """Encapsulates in-memory session tracking for a single thread in BaselineAgent.

    Attributes:
        messages: Chronological list of message dictionaries ('role', 'content').
        token_usage: Cumulative tokens generated by the assistant in this session.
        prompt_tokens_processed: Cumulative prompt context tokens fed to the model in this session.
    """

    messages: list[dict[str, str]] = field(default_factory=list)
    token_usage: int = 0
    prompt_tokens_processed: int = 0


class BaselineAgent:
    """Baseline conversational agent with within-session short-term memory only (Agent A).

    Characteristics:
        - Memory is strictly partitioned by `thread_id` in RAM.
        - Has no persistent storage (no `User.md`).
        - Forgets all user facts when addressed in a fresh thread.
        - Has no compaction: prompt tokens processed grow quadratically with conversation length.
    """

    def __init__(self, config: LabConfig | None = None, force_offline: bool = False) -> None:
        """Initialize BaselineAgent with configuration and execution mode.

        Args:
            config: LabConfig instance. Defaults to load_config() if not provided.
            force_offline: If True, forces deterministic offline execution without LLM API calls.
        """
        self.config = config or load_config()
        self.force_offline = force_offline
        self.sessions: dict[str, SessionState] = {}
        self.langchain_agent = self._maybe_build_langchain_agent()

    def reply(self, user_id: str, thread_id: str, message: str) -> dict[str, Any]:
        """Dispatch a user message to either the live LangGraph agent or deterministic offline mode.

        Args:
            user_id: Unique user identifier.
            thread_id: Conversation thread identifier.
            message: User input message text.

        Returns:
            Dictionary with keys 'response' (str), 'tokens' (int), and 'prompt_tokens' (int).
        """
        if not self.force_offline and self.langchain_agent is not None:
            try:
                config = {"configurable": {"thread_id": thread_id}}
                result = self.langchain_agent.invoke(
                    {"messages": [{"role": "user", "content": message}]},
                    config=config,
                )
                messages = result.get("messages", [])
                response_text = messages[-1].content if messages else "Đã ghi nhận."
                resp_tokens = estimate_tokens(response_text)
                prompt_tokens = estimate_tokens(message)
                return {
                    "response": response_text,
                    "tokens": resp_tokens,
                    "prompt_tokens": prompt_tokens,
                }
            except Exception:
                pass

        return self._reply_offline(thread_id, message)

    def token_usage(self, thread_id: str | None = None) -> int:
        """Return cumulative assistant response tokens generated for a thread or all threads.

        Args:
            thread_id: Optional thread identifier. If None, returns total across all sessions.

        Returns:
            Integer total token count.
        """
        if thread_id is not None:
            return self.sessions.get(thread_id, SessionState()).token_usage
        return sum(s.token_usage for s in self.sessions.values())

    def prompt_token_usage(self, thread_id: str | None = None) -> int:
        """Estimate cumulative prompt context tokens processed for a thread or all threads.

        Args:
            thread_id: Optional thread identifier. If None, returns total across all sessions.

        Returns:
            Integer total prompt context token count.
        """
        if thread_id is not None:
            return self.sessions.get(thread_id, SessionState()).prompt_tokens_processed
        return sum(s.prompt_tokens_processed for s in self.sessions.values())

    def compaction_count(self, thread_id: str | None = None) -> int:
        """Return compaction count for BaselineAgent. Always 0 since Baseline has no compaction.

        Args:
            thread_id: Optional thread identifier.

        Returns:
            Always 0.
        """
        return 0

    def _reply_offline(self, thread_id: str, message: str) -> dict[str, Any]:
        """Generate a deterministic response and track prompt context accumulation offline.

        In a fresh thread, Baseline forgets all past user facts. Within an existing thread,
        it drags along the full message history without compaction.

        Args:
            thread_id: Conversation thread identifier.
            message: Incoming user message text.

        Returns:
            Dictionary with keys 'response', 'tokens', and 'prompt_tokens'.
        """
        if thread_id not in self.sessions:
            self.sessions[thread_id] = SessionState()

        session = self.sessions[thread_id]

        # In baseline, previous turns in different threads are completely unknown!
        is_fresh_thread = len(session.messages) == 0

        # Append user message
        session.messages.append({"role": "user", "content": message})

        # Prompt tokens in baseline include the entire history of this thread so far
        prompt_tokens = sum(estimate_tokens(m["content"]) for m in session.messages)
        session.prompt_tokens_processed += prompt_tokens

        # Generate response: if fresh thread, baseline has zero knowledge of past user facts
        m_lower = message.lower()
        is_recall_question = any(
            k in m_lower
            for k in [
                "nhắc lại", "tên mình", "mình tên gì", "ở đâu", "nơi ở", "nghề", "làm gì",
                "đồ uống", "món ăn", "nuôi con gì", "style", "kiểu trả lời", "mối quan tâm",
                "tóm tắt ngắn về mình", "dũngct là ai", "đâu mới là", "sang thread mới",
            ]
        )

        if is_fresh_thread and is_recall_question:
            response_text = "Xin chào! Mình chưa có thông tin về bạn trong phiên trò chuyện này. Bạn có thể chia sẻ lại không?"
        elif is_recall_question:
            # Check if mentioned earlier in THIS session
            history_text = " ".join(m["content"] for m in session.messages[:-1])
            if "dũngct" in history_text.lower():
                response_text = "Dựa trên hội thoại trong phiên này, bạn có tên là DũngCT."
            else:
                response_text = "Trong phiên này mình chưa thấy bạn nhắc đến thông tin đó."
        else:
            response_text = "Chào bạn, mình đã ghi nhận thông tin trong phiên trò chuyện hiện tại."

        # Append assistant reply
        session.messages.append({"role": "assistant", "content": response_text})
        resp_tokens = estimate_tokens(response_text)
        session.token_usage += resp_tokens

        return {
            "response": response_text,
            "tokens": resp_tokens,
            "prompt_tokens": prompt_tokens,
        }

    def _maybe_build_langchain_agent(self):
        """Construct a live LangGraph ReAct agent if an API key is configured.

        Returns:
            Compiled StateGraph agent if live mode is possible, or None otherwise.
        """
        if self.force_offline or not self.config.model.api_key:
            return None
        try:
            from langgraph.checkpoint.memory import InMemorySaver
            from langgraph.prebuilt import create_react_agent

            chat_model = build_chat_model(self.config.model)
            checkpointer = InMemorySaver()
            return create_react_agent(chat_model, tools=[], checkpointer=checkpointer)
        except Exception:
            return None
